# 1. 선형 회귀 구현

In [1]:
import torch
torch.cuda.is_available()

/root/anaconda3/envs/nlp/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


False

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [4]:
print(x_train, x_train.shape)
print(y_train, y_train.shape)

tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])


### weight, bias 초기화

In [5]:
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [6]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


### 직선의 방정식 $ H(x)= Wx+b$ 선언

In [7]:
H = W * x_train + b

### 평균제곱오차 선언 $$ cost(W, b) = \frac{1}{n} \sum_{i=1}^{n} \left[y^{(i)} - H(x^{(i)})\right]^2 $$ 

In [9]:
cost = torch.mean((H - y_train)**2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


In [10]:
# optimizer 정의
optimizer = optim.SGD([W, b], lr=0.01)

In [11]:
# gradient를 0으로 초기화
optimizer.zero_grad()

# 비용 함수를 미분하여 gradienr 계산
cost.backward()

# W와 b를 업데이트
optimizer.step()

### 학습

In [12]:
torch. manual_seed(1)

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

# gradient descent 반복
epochs = 2000

for epoch in range(1, epochs+1):

    # H(x) 계산
    H = x_train *W + b

    # cost 계산
    cost = torch.mean((H-y_train)**2)

    # cost로 H(x) 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번 마다 로그 출력
    if epoch % 100 == 0:
            print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
                epoch, epochs, W.item(), b.item(), cost.item()
            ))


Epoch  100/2000 W: 0.873, b: 0.290 Cost: 0.012101
Epoch  200/2000 W: 0.900, b: 0.228 Cost: 0.007478
Epoch  300/2000 W: 0.921, b: 0.179 Cost: 0.004621
Epoch  400/2000 W: 0.938, b: 0.141 Cost: 0.002855
Epoch  500/2000 W: 0.951, b: 0.111 Cost: 0.001764
Epoch  600/2000 W: 0.962, b: 0.087 Cost: 0.001090
Epoch  700/2000 W: 0.970, b: 0.068 Cost: 0.000674
Epoch  800/2000 W: 0.976, b: 0.054 Cost: 0.000416
Epoch  900/2000 W: 0.981, b: 0.042 Cost: 0.000257
Epoch 1000/2000 W: 0.985, b: 0.033 Cost: 0.000159
Epoch 1100/2000 W: 0.989, b: 0.026 Cost: 0.000098
Epoch 1200/2000 W: 0.991, b: 0.021 Cost: 0.000061
Epoch 1300/2000 W: 0.993, b: 0.016 Cost: 0.000038
Epoch 1400/2000 W: 0.994, b: 0.013 Cost: 0.000023
Epoch 1500/2000 W: 0.996, b: 0.010 Cost: 0.000014
Epoch 1600/2000 W: 0.997, b: 0.008 Cost: 0.000009
Epoch 1700/2000 W: 0.997, b: 0.006 Cost: 0.000005
Epoch 1800/2000 W: 0.998, b: 0.005 Cost: 0.000003
Epoch 1900/2000 W: 0.998, b: 0.004 Cost: 0.000002
Epoch 2000/2000 W: 0.999, b: 0.003 Cost: 0.000001


# 2. optimizer.zero_grad()가 필요한 이유

In [18]:
import torch

w = torch.tensor(2.0, requires_grad=True)

epochs=20
for epoch in range(1, epochs+1):

    z = 2 * w
    z.backward()
    print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 2.0
수식을 w로 미분한 값: 4.0
수식을 w로 미분한 값: 6.0
수식을 w로 미분한 값: 8.0
수식을 w로 미분한 값: 10.0
수식을 w로 미분한 값: 12.0
수식을 w로 미분한 값: 14.0
수식을 w로 미분한 값: 16.0
수식을 w로 미분한 값: 18.0
수식을 w로 미분한 값: 20.0
수식을 w로 미분한 값: 22.0
수식을 w로 미분한 값: 24.0
수식을 w로 미분한 값: 26.0
수식을 w로 미분한 값: 28.0
수식을 w로 미분한 값: 30.0
수식을 w로 미분한 값: 32.0
수식을 w로 미분한 값: 34.0
수식을 w로 미분한 값: 36.0
수식을 w로 미분한 값: 38.0
수식을 w로 미분한 값: 40.0
